server:
  port: 8079

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - DedupeResponseHeader=Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account-service/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/api/v1/item-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order-service/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment-service/**
        - id: shopping-cart-service
          uri: lb://shopping-cart-service
          predicates:
            - Path=/api/v1/shopping-cart-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # eureka-service -> localhost run in local
      register-with-eureka: true
      fetch-registry: true
  instance:
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000  # 7天

logging:
  level:
    org.springframework.security: DEBUG
    com.future.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO