package com.future.futurecommon.constant;

public enum OrderEventType {
    ORDER_CREATED, ORDER_UPDATED, ORDER_CONFIRMED, ORDER_CANCELLED, ORDER_SHIPPED, ORDER_DELIVERED,
    PAYMENT_SUCCESS, PAYMENT_FAILED, PAYMENT_REFUNDED
}
